default: &default
  pool: 5
  adapter: postgresql
  encoding: unicode

  database: petmatch_test
  username: petmatch_dev
  password: <%= ENV["PETMATCH_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: petmatch_development
  username: petmatch_dev

test:
  <<: *default
  database: petmatch_test
  username: petmatch_dev

production:
  <<: *default
  database: petmatch_production
  username: petmatch_dev
